/*
 * @Description:
 */
export const DictEN = {
  //数据字典
  DATA_DICTIONARY_SEARCH_PLACEHOLDER: 'Search Dictionary Name/Dictionary Code',
  DATA_DICTIONARY_ADD: 'Add Dictionary',
  DATA_DICTIONARY: 'Dictionary',

  ADD_DATA_DICTIONARY: 'Add',
  EDIT_DATA_DICTIONARY: 'Edit',
  DELETE_DATA_DICTIONARY: 'Delete',
  CONFIG_DATA_DICTIONARY: 'Config',

  DATA_DICTIONARY_DIALOG_DIC_NAME: 'Name',
  DATA_DICTIONARY_DIALOG_DIC_CODE: 'Code',
  DATA_DICTIONARY_DIALOG_DIC_TYPE: 'Source',
  DATA_DICTIONARY_DIALOG_DIC_VALUE: 'ConfigContent',
  DATA_DICTIONARY_DIALOG_DIC_REMARK: 'Remark',

  DATA_DICTIONARY_DIALOG_DIC_NAME_PLACEHOLDER: 'Please enter the dictionary name', //新增字典-字典名称
  DATA_DICTIONARY_DIALOG_DIC_CODE_PLACEHOLDER: 'Please enter the dictionary code', //新增字典-字典编码
  DATA_DICTIONARY_DIALOG_DIC_TYPE_PLACEHOLDER: 'Please enter the parameter type', //新增字典-参数类型

  DATA_DICTIONARY_TYPES_ENUM: 'Manual Entry',
  DATA_DICTIONARY_TYPES_API: 'Remote Request',
  DATA_DICTIONARY_TYPES_SCRIPT: 'Generated by Script',

  ENUM: 'Enum',
  SCRIPT: 'Script',

  DATA_DICTIONARY_CONFIG_DIALOG_SEARCH_PLACEHOLDER: 'Search Dictionary Item/Code',
  DATA_DICTIONARY_CONFIG_DIALOG_CURRENT_DIC: 'Current Dictionary:',

  DATA_DICTIONARY_CONFIG_DIALOG_TABLE_COLUMNS: [
    'Index',
    'DictionaryItem',
    'Code',
    'Source',
    'Status',
    'Order',
    'Remark',
    'Operation',
  ],
  BUILT_IN_DICTIONARY_NOT_DEL: 'Built-in dictionaries cannot be deleted',
  DELETE_DIC_WARNING_MESSAGE: 'Confirm to delete the current dictionary?',
};
