import mitt from 'mitt';

const bus = mitt();

export { bus };
// 数据字典
export const DATA_DICTIONARY_SHOW_DIALOG_ADD = 'DATA_DICTIONARY_SHOW_DIALOG_ADD';
export const DATA_DICTIONARY_SHOW_DIALOG_CONFIG = 'DATA_DICTIONARY_SHOW_DIALOG_CONFIG';
// 用户管理
export const USER_MANAGE_SHOW_DIALOG_EMPOWER_TO_USER = 'USER_MANAGE_SHOW_DIALOG_EMPOWER_TO_USER';

// 组织树变化，已授权数据修改
export const ORGANIZATION_TREE_DATA_CHANGE = 'ORGANIZATION_TREE_DATA_CHANGE';
export const AUTHORIZED_DATA_CHANGE = 'AUTHORIZED_DATA_CHANGE';
export const ORGANIZATION_TREE_NODE_CLICK = 'ORGANIZATION_TREE_NODE_CLICK';
// 消息状态，删除，更新SSE控件列表
export const MESSAGE_STATE_CHANGE = 'MESSAGE_STATE_CHANGE';
export const MESSAGE_SSE_NOTIFICATION_CHANGE = 'MESSAGE_SSE_NOTIFICATION_CHANGE';
// token存储后
export const TOKEN_ID_SAVED = 'TOKEN_ID_SAVED';
// 页面右上角返回通知页面做拦截
export const PAGE_BACK = 'PAGE_BACK';
//树形结构展开
export const TREE_EXPAND = 'TREE_EXPAND';
export const FORM_SHOW_DIALOG_ADD = 'FORM_SHOW_DIALOG_ADD';
// 选择组织水厂
export const SELECT_FACTORY = 'SELECT_FACTORY';
// 增加自定义产品
export const ADD_CUSTOM_PRODUCT = 'ADD_CUSTOM_PRODUCT';
// 增加自定义产品回调
export const ADD_CUSTOM_PRODUCT_CALLBACK = 'ADD_CUSTOM_PRODUCT_CALLBACK';
