
export interface TableDataItem {
  modelId: string // 模型modelId
  modelName: string // 模型名称
  type: string // 模型类型
  notes: string // 功能描述
  inputParameters: string // 输入数据
  outputParameters: string // 输出结果
  applicableScenario: string // 应用场景
  metrics: string // 评估指标
  releaseStatus: string // 发布状态
  createdAt: string // 创建时间
  modelVersion: string // 当前版本
  lastUpdated: string // 最近更新时间
    is_public?: string | boolean
    owner?: string
    developLanguage?: string
    framework?: string
    hardware?: any,
    accuracy?: string
    license: string
    deployment: string
}

export const mockTableData: TableDataItem[] = [{
  "modelId": "XXX智能体编号",
  "modelName": "XXX业务智能体",
  "type": "智能体",
  "is_public": "XXX公开状态智能体",
  "owner": "XXX所属机构智能体",
  "developLanguage": "XXX编程语言智能体",
  "applicableScenario": "XXX应用场景智能体",
  "notes": "XXX功能描述智能体",
  "inputParameters": "XXX输入数据智能体",
  "outputParameters": "XXX输出结果智能体",
  "metrics": "XXX性能指标智能体",
  "releaseStatus": "发布",
  "modelVersion": "XXX版本号智能体",
  "framework": "XXX算法框架智能体",
  "hardware": ["XXX硬件要求智能体"],
  "accuracy": "XXX精度指标智能体",
  "license": "XXX许可协议智能体",
  "deployment": "XXX部署方式智能体",
  "createdAt": "2024-01-15",
  "lastUpdated": "2025-08-10"

},
{
  "modelId": "WA001",
  "modelName": "智能曝气优化器",
  "type": "智能体",
  "is_public": true,
  "owner": "智慧水务集团",
  "developLanguage": "Python",
  "applicableScenario": "生物池溶解氧控制",
  "notes": "动态调节曝气量实现节能降耗",
  "inputParameters": "DO、MLSS、进水流量、温度",
  "outputParameters": "曝气设备控制参数",
  "metrics": "节能率15%±2%",
  "releaseStatus": "发布",
  "modelVersion": "v3.2.1",
  "framework": "TensorFlow",
  "hardware": ["GPU"],
  "accuracy": "DO控制偏差±0.3mg/L",
  "license": "Apache 2.0",
  "deployment": "边缘计算",
  "createdAt": "2024-01-15",
  "lastUpdated": "2025-08-10"
},
{
  "modelId": "WA002",
  "modelName": "污泥膨胀预警机",
  "type": "智能体",
  "is_public": false,
  "owner": "蓝科环境实验室",
  "developLanguage": "R",
  "applicableScenario": "二沉池运行监控",
  "notes": "提前48小时预警污泥膨胀风险",
  "inputParameters": "SVI、MLSS、F/M比",
  "outputParameters": "风险等级(1-5级)",
  "metrics": "召回率92%",
  "releaseStatus": "发布",
  "modelVersion": "v1.8.3",
  "framework": "PyTorch",
  "hardware": ["CPU"],
  "accuracy": "误报率<8%",
  "license": "MIT",
  "deployment": "云平台",
  "createdAt": "2023-09-20",
  "lastUpdated": "2025-07-30"
},
{
  "modelId": "WA003",
  "modelName": "加药智能决策系统",
  "type": "智能体",
  "is_public": true,
  "owner": "市政污水处理厂",
  "developLanguage": "Julia",
  "applicableScenario": "化学除磷控制",
  "notes": "平衡药剂成本与出水TP达标",
  "inputParameters": "进水TP、流量、pH",
  "outputParameters": "PAC投加量(g/m³)",
  "metrics": "年节约药剂费23万元",
  "releaseStatus": "发布",
  "modelVersion": "v2.5.0",
  "framework": "JAX",
  "hardware": ["TPU"],
  "accuracy": "TP达标率99.2%",
  "license": "BSD",
  "deployment": "混合部署",
  "createdAt": "2022-12-05",
  "lastUpdated": "2025-06-18"
},
{
  "modelId": "WA004",
  "modelName": "管网淤堵预测模型",
  "type": "智能体",
  "is_public": false,
  "owner": "排水管网公司",
  "developLanguage": "Java",
  "applicableScenario": "污水管网维护",
  "notes": "预测管网淤堵位置及严重程度",
  "inputParameters": "流速、水位、历史维护记录",
  "outputParameters": "淤堵概率热力图",
  "metrics": "AUC=0.89",
  "releaseStatus": "发布",
  "modelVersion": "v0.9.7",
  "framework": "DGL",
  "hardware": ["GPU"],
  "accuracy": "定位误差±15m",
  "license": "自定义",
  "deployment": "本地服务器",
  "createdAt": "2025-03-12",
  "lastUpdated": "2025-08-15"
},
{
  "modelId": "WA005",
  "modelName": "能耗数字孪生体",
  "type": "智能体",
  "is_public": true,
  "owner": "国家节能中心",
  "developLanguage": "C++",
  "applicableScenario": "全厂能耗分析",
  "notes": "建立设备级能耗仿真模型",
  "inputParameters": "设备运行参数、电价时段",
  "outputParameters": "能耗优化方案",
  "metrics": "仿真误差<5%",
  "releaseStatus": "发布",
  "modelVersion": "v4.0.2",
  "framework": "OpenFOAM",
  "hardware": ["HPC"],
  "accuracy": "峰谷电费节省18%",
  "license": "GPL",
  "deployment": "超算中心",
  "createdAt": "2021-11-30",
  "lastUpdated": "2025-05-22"
},
{
  "modelId": "WA006",
  "modelName": "恶臭扩散模拟器",
  "type": "智能体",
  "is_public": false,
  "owner": "环境监测站",
  "developLanguage": "Fortran",
  "applicableScenario": "厂界臭气浓度预测",
  "notes": "模拟H2S在不同气象条件下的扩散",
  "inputParameters": "气象数据、源强参数",
  "outputParameters": "浓度等值线图",
  "metrics": "R²=0.85",
  "releaseStatus": "发布",
  "modelVersion": "v1.2.4",
  "framework": "ANSYS",
  "hardware": ["GPU集群"],
  "accuracy": "监测点误差±10%",
  "license": "商业许可",
  "deployment": "私有云",
  "createdAt": "2024-06-08",
  "lastUpdated": "2025-07-11"
},
{
  "modelId": "WA007",
  "modelName": "智能除砂机器人",
  "type": "智能体",
  "is_public": true,
  "owner": "自动化设备厂",
  "developLanguage": "Python",
  "applicableScenario": "沉砂池清理",
  "notes": "基于图像识别自动调节除砂频率",
  "inputParameters": "水下摄像头画面",
  "outputParameters": "除砂机启停指令",
  "metrics": "砂粒去除率95%",
  "releaseStatus": "发布",
  "modelVersion": "v3.1.0",
  "framework": "OpenCV",
  "hardware": ["嵌入式GPU"],
  "accuracy": "识别准确率97%",
  "license": "LGPL",
  "deployment": "边缘设备",
  "createdAt": "2023-04-17",
  "lastUpdated": "2025-08-05"
},
{
  "modelId": "WA008",
  "modelName": "污泥热值分析仪",
  "type": "智能体",
  "is_public": false,
  "owner": "固废处理中心",
  "developLanguage": "MATLAB",
  "applicableScenario": "污泥焚烧优化",
  "notes": "实时检测脱水污泥热值特性",
  "inputParameters": "NIR光谱数据",
  "outputParameters": "热值(kcal/kg)",
  "metrics": "RMSECV=120kcal/kg",
  "releaseStatus": "发布",
  "modelVersion": "v2.3.5",
  "framework": "PLS工具箱",
  "hardware": ["光谱仪"],
  "accuracy": "与实验室结果相关系数0.94",
  "license": "科研专用",
  "deployment": "现场工控机",
  "createdAt": "2024-02-28",
  "lastUpdated": "2025-06-30"
},
{
  "modelId": "WA009",
  "modelName": "出水水质预测器",
  "type": "智能体",
  "is_public": true,
  "owner": "环境大数据平台",
  "developLanguage": "Python",
  "applicableScenario": "工艺调控预警",
  "notes": "提前2小时预测出水COD/TN超标",
  "inputParameters": "在线仪表数据",
  "outputParameters": "超标概率",
  "metrics": "F1=0.88",
  "releaseStatus": "发布",
  "modelVersion": "v5.0.0",
  "framework": "XGBoost",
  "hardware": ["云服务器"],
  "accuracy": "预警准确率90%",
  "license": "AGPL",
  "deployment": "SaaS平台",
  "createdAt": "2020-08-10",
  "lastUpdated": "2025-08-12"
},
{
  "modelId": "WA010",
  "modelName": "设备故障诊断专家",
  "type": "智能体",
  "is_public": false,
  "owner": "设备制造商",
  "developLanguage": "Prolog",
  "applicableScenario": "预防性维护",
  "notes": "基于振动频谱诊断泵机故障类型",
  "inputParameters": "加速度传感器数据",
  "outputParameters": "故障代码",
  "metrics": "诊断准确率93%",
  "releaseStatus": "发布",
  "modelVersion": "v1.0.0",
  "framework": "Neo4j",
  "hardware": ["工业网关"],
  "accuracy": "提前预警时间≥72h",
  "license": "商业机密",
  "deployment": "本地化部署",
  "createdAt": "2025-01-05",
  "lastUpdated": "2025-07-28"
},



    {
        "modelId": "WA010",
        "modelName": "设备故障诊断专家",
        "type": "智能体",
        "is_public": false,
        "owner": "设备制造商",
        "developLanguage": "Prolog",
        "applicableScenario": "预防性维护",
        "notes": "基于振动频谱诊断泵机故障类型",
        "inputParameters": "加速度传感器数据",
        "outputParameters": "故障代码",
        "metrics": "诊断准确率93%",
        "releaseStatus": "发布",
        "modelVersion": "v1.0.0",
        "framework": "Neo4j",
        "hardware": ["工业网关"],
        "accuracy": "提前预警时间≥72h",
        "license": "商业机密",
        "deployment": "本地化部署",
        "createdAt": "2025-01-05",
        "lastUpdated": "2025-07-28"
    },
    {
        "modelId": "WA010",
        "modelName": "设备故障诊断专家",
        "type": "智能体",
        "is_public": false,
        "owner": "设备制造商",
        "developLanguage": "Prolog",
        "applicableScenario": "预防性维护",
        "notes": "基于振动频谱诊断泵机故障类型",
        "inputParameters": "加速度传感器数据",
        "outputParameters": "故障代码",
        "metrics": "诊断准确率93%",
        "releaseStatus": "发布",
        "modelVersion": "v1.0.0",
        "framework": "Neo4j",
        "hardware": ["工业网关"],
        "accuracy": "提前预警时间≥72h",
        "license": "商业机密",
        "deployment": "本地化部署",
        "createdAt": "2025-01-05",
        "lastUpdated": "2025-07-28"
    },
    {
        "modelId": "WA010",
        "modelName": "设备故障诊断专家",
        "type": "智能体",
        "is_public": false,
        "owner": "设备制造商",
        "developLanguage": "Prolog",
        "applicableScenario": "预防性维护",
        "notes": "基于振动频谱诊断泵机故障类型",
        "inputParameters": "加速度传感器数据",
        "outputParameters": "故障代码",
        "metrics": "诊断准确率93%",
        "releaseStatus": "发布",
        "modelVersion": "v1.0.0",
        "framework": "Neo4j",
        "hardware": ["工业网关"],
        "accuracy": "提前预警时间≥72h",
        "license": "商业机密",
        "deployment": "本地化部署",
        "createdAt": "2025-01-05",
        "lastUpdated": "2025-07-28"
    },
    {
        "modelId": "WA010",
        "modelName": "设备故障诊断专家",
        "type": "智能体",
        "is_public": false,
        "owner": "设备制造商",
        "developLanguage": "Prolog",
        "applicableScenario": "预防性维护",
        "notes": "基于振动频谱诊断泵机故障类型",
        "inputParameters": "加速度传感器数据",
        "outputParameters": "故障代码",
        "metrics": "诊断准确率93%",
        "releaseStatus": "发布",
        "modelVersion": "v1.0.0",
        "framework": "Neo4j",
        "hardware": ["工业网关"],
        "accuracy": "提前预警时间≥72h",
        "license": "商业机密",
        "deployment": "本地化部署",
        "createdAt": "2025-01-05",
        "lastUpdated": "2025-07-28"
    },
    {
        "modelId": "WA010",
        "modelName": "设备故障诊断专家",
        "type": "智能体",
        "is_public": false,
        "owner": "设备制造商",
        "developLanguage": "Prolog",
        "applicableScenario": "预防性维护",
        "notes": "基于振动频谱诊断泵机故障类型",
        "inputParameters": "加速度传感器数据",
        "outputParameters": "故障代码",
        "metrics": "诊断准确率93%",
        "releaseStatus": "发布",
        "modelVersion": "v1.0.0",
        "framework": "Neo4j",
        "hardware": ["工业网关"],
        "accuracy": "提前预警时间≥72h",
        "license": "商业机密",
        "deployment": "本地化部署",
        "createdAt": "2025-01-05",
        "lastUpdated": "2025-07-28"
    },
    {
        "modelId": "WA010",
        "modelName": "设备故障诊断专家",
        "type": "智能体",
        "is_public": false,
        "owner": "设备制造商",
        "developLanguage": "Prolog",
        "applicableScenario": "预防性维护",
        "notes": "基于振动频谱诊断泵机故障类型",
        "inputParameters": "加速度传感器数据",
        "outputParameters": "故障代码",
        "metrics": "诊断准确率93%",
        "releaseStatus": "发布",
        "modelVersion": "v1.0.0",
        "framework": "Neo4j",
        "hardware": ["工业网关"],
        "accuracy": "提前预警时间≥72h",
        "license": "商业机密",
        "deployment": "本地化部署",
        "createdAt": "2025-01-05",
        "lastUpdated": "2025-07-28"
    },
    {
        "modelId": "WA010",
        "modelName": "设备故障诊断专家",
        "type": "智能体",
        "is_public": false,
        "owner": "设备制造商",
        "developLanguage": "Prolog",
        "applicableScenario": "预防性维护",
        "notes": "基于振动频谱诊断泵机故障类型",
        "inputParameters": "加速度传感器数据",
        "outputParameters": "故障代码",
        "metrics": "诊断准确率93%",
        "releaseStatus": "发布",
        "modelVersion": "v1.0.0",
        "framework": "Neo4j",
        "hardware": ["工业网关"],
        "accuracy": "提前预警时间≥72h",
        "license": "商业机密",
        "deployment": "本地化部署",
        "createdAt": "2025-01-05",
        "lastUpdated": "2025-07-28"
    },
    {
        "modelId": "WA010",
        "modelName": "设备故障诊断专家",
        "type": "智能体",
        "is_public": false,
        "owner": "设备制造商",
        "developLanguage": "Prolog",
        "applicableScenario": "预防性维护",
        "notes": "基于振动频谱诊断泵机故障类型",
        "inputParameters": "加速度传感器数据",
        "outputParameters": "故障代码",
        "metrics": "诊断准确率93%",
        "releaseStatus": "发布",
        "modelVersion": "v1.0.0",
        "framework": "Neo4j",
        "hardware": ["工业网关"],
        "accuracy": "提前预警时间≥72h",
        "license": "商业机密",
        "deployment": "本地化部署",
        "createdAt": "2025-01-05",
        "lastUpdated": "2025-07-28"
    },

]
export const mockTreeData = []